### ISSUE TITLE
在wsl中的錯誤

### ISSUE THREAD

**Issue by win10ogod** [neromous/RWKV-Ouroboros#3]
```
 [WARNING]  cpu_adam cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
Using /root/.cache/torch_extensions/py310_cu117 as PyTorch extensions root...
Emitting ninja build file /root/.cache/torch_extensions/py310_cu117/cpu_adam/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module cpu_adam...
Time to load cpu_adam op: 3.7531509399414062 seconds
RWKV_MY_TESTING
Using /root/.cache/torch_extensions/py310_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py310_cu117/wkv_1024/build.ninja...
Building extension module wkv_1024...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module wkv_1024...
0it [00:00, ?it/s]
total [] files  has 0 items.
0it [00:00, ?it/s]
0it [00:00, ?it/s]
total [] files  has 0 items.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/root/RWKV-Ouroboros/app.py", line 76, in <module>
    load_dict = torch.load(args.load_model, map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/neromous/pyblackfog/rwkv-output-models/3b/rwkv-9.pth'
[2023-09-14 17:38:32,749] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 589
[2023-09-14 17:38:32,749] [ERROR] [launch.py:321:sigkill_handler] ['/usr/bin/python3', '-u', 'app.py', '--local_rank=0', '--deepspeed', '--deepspeed_config', 'ds_config.config'] exits with return code = 1
```

**Comment by win10ogod** [comment]
@neromous 您能幫我在Windows 子系統Linux 版 wsl跑起項目嗎?

**Comment by neromous** [comment]
> @neromous 您能幫我在Windows 子系統Linux 版 wsl跑起項目嗎?
先更新项目， 过去的项目中有若干错误已经修正，然后你需要把config.json中的load_model 修改为你的模型

建议你等待我后面的版本重构， 等过两天push上新的基于infctx的版本，同时数据模型加载会给个示例。

**Comment by win10ogod** [comment]
> > @neromous 您能幫我在Windows 子系統Linux 版 wsl跑起項目嗎?
> > 先更新项目， 过去的项目中有若干错误已经修正，然后你需要把config.json中的load_model 修改为你的模型
> 
> 建议你等待我后面的版本重构， 等过两天push上新的基于infctx的版本，同时数据模型加载会给个示例。

感謝您的回覆

**Comment by win10ogod** [comment]
> > @neromous 您能幫我在Windows 子系統Linux 版 wsl跑起項目嗎?
> > 先更新项目， 过去的项目中有若干错误已经修正，然后你需要把config.json中的load_model 修改为你的模型
> 
> 建议你等待我后面的版本重构， 等过两天push上新的基于infctx的版本，同时数据模型加载会给个示例。

```
[2023-09-15 12:14:20,769] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 12:14:21,792] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-09-15 12:14:21,831] [INFO] [runner.py:555:main] cmd = /usr/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None app.py --deepspeed --deepspeed_config ds_config.config
[2023-09-15 12:14:22,357] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 12:14:22,865] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0]}
[2023-09-15 12:14:22,865] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-09-15 12:14:22,865] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-09-15 12:14:22,865] [INFO] [launch.py:163:main] dist_world_size=1
[2023-09-15 12:14:22,865] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0
[2023-09-15 12:14:23,412] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[RWKV.model] Running RWKV model using 'torch-jit' with torch '1.13.1+cu117'
[{'id': 5, 'title': 'dddddd', 'completed': False, 'ct': 1694705822, 'ut': 1694705822}, {'id': 6, 'title': 'dddddd', 'completed': False, 'ct': 1694705829, 'ut': 1694705829}, {'id': 7, 'title': 'dddddd', 'completed': False, 'ct': 1694705966, 'ut': 1694705966}, {'id': 8, 'title': 'dddddd', 'completed': False, 'ct': 1694705976, 'ut': 1694705976}, {'id': 9, 'title': 'dddddd', 'completed': False, 'ct': 1694706174, 'ut': 1694706174}, {'id': 10, 'title': 'dddddd', 'completed': False, 'ct': 1694706542, 'ut': 1694706542}, {'id': 11, 'title': 'dddddd', 'completed': False, 'ct': 1694706571, 'ut': 1694706571}, {'id': 12, 'title': 'dddddd', 'completed': False, 'ct': 1694706594, 'ut': 1694706594}, {'id': 13, 'title': 'dddddd', 'completed': False, 'ct': 1694707342, 'ut': 1694707342}, {'id': 14, 'title': 'dddddd', 'completed': False, 'ct': 1694707490, 'ut': 1694707490}, {'id': 15, 'title': 'dddddd', 'completed': False, 'ct': 1694740785, 'ut': 1694740785}, {'id': 16, 'title': 'dddddd', 'completed': False, 'ct': 1694740881, 'ut': 1694740881}, {'id': 17, 'title': 'dddddd', 'completed': False, 'ct': 1694740939, 'ut': 1694740939}, {'id': 18, 'title': 'dddddd', 'completed': False, 'ct': 1694740971, 'ut': 1694740971}, {'id': 19, 'title': 'dddddd', 'completed': False, 'ct': 1694741018, 'ut': 1694741018}, {'id': 20, 'title': 'dddddd', 'completed': False, 'ct': 1694741036, 'ut': 1694741036}, {'id': 21, 'title': 'dddddd', 'completed': False, 'ct': 1694742835, 'ut': 1694742835}, {'id': 22, 'title': 'dddddd', 'completed': False, 'ct': 1694742852, 'ut': 1694742852}, {'id': 23, 'title': 'dddddd', 'completed': False, 'ct': 1694742875, 'ut': 1694742875}, {'id': 24, 'title': 'dddddd', 'completed': False, 'ct': 1694744839, 'ut': 1694744839}, {'id': 25, 'title': 'dddddd', 'completed': False, 'ct': 1694744867, 'ut': 1694744867}, {'id': 26, 'title': 'dddddd', 'completed': False, 'ct': 1694745034, 'ut': 1694745034}, {'id': 27, 'title': 'dddddd', 'completed': False, 'ct': 1694745051, 'ut': 1694745051}, {'id': 28, 'title': 'dddddd', 'completed': False, 'ct': 1694745237, 'ut': 1694745237}, {'id': 29, 'title': 'dddddd', 'completed': False, 'ct': 1694745384, 'ut': 1694745384}, {'id': 30, 'title': 'dddddd', 'completed': False, 'ct': 1694745889, 'ut': 1694745889}, {'id': 31, 'title': 'dddddd', 'completed': False, 'ct': 1694746101, 'ut': 1694746101}, {'id': 32, 'title': 'dddddd', 'completed': False, 'ct': 1694746182, 'ut': 1694746182}, {'id': 33, 'title': 'dddddd', 'completed': False, 'ct': 1694746366, 'ut': 1694746366}, {'id': 34, 'title': 'dddddd', 'completed': False, 'ct': 1694746401, 'ut': 1694746401}, {'id': 35, 'title': 'dddddd', 'completed': False, 'ct': 1694746898, 'ut': 1694746898}, {'id': 36, 'title': 'dddddd', 'completed': False, 'ct': 1694751000, 'ut': 1694751000}, {'id': 37, 'title': 'dddddd', 'completed': False, 'ct': 1694751113, 'ut': 1694751113}, {'id': 38, 'title': 'dddddd', 'completed': False, 'ct': 1694751131, 'ut': 1694751131}]
[{'id': 1, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 2, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 3, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 4, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 5, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 6, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 7, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 8, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 9, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 10, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 11, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 12, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 13, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 14, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 15, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 16, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 17, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 18, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 19, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 20, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 21, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 22, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 23, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 24, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 25, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 26, 'instruction': 'dfafdfa', 'input': '', 'response': ''}, {'id': 27, 'instruction': 'dfafdfa', 'input': '', 'response': ''}]
[{'id': 5, 'title': 'dddddd', 'completed': False, 'ct': 1694705822, 'ut': 1694705822}, {'id': 6, 'title': 'dddddd', 'completed': False, 'ct': 1694705829, 'ut': 1694705829}, {'id': 7, 'title': 'dddddd', 'completed': False, 'ct': 1694705966, 'ut': 1694705966}, {'id': 8, 'title': 'dddddd', 'completed': False, 'ct': 1694705976, 'ut': 1694705976}, {'id': 9, 'title': 'dddddd', 'completed': False, 'ct': 1694706174, 'ut': 1694706174}, {'id': 10, 'title': 'dddddd', 'completed': False, 'ct': 1694706542, 'ut': 1694706542}, {'id': 11, 'title': 'dddddd', 'completed': False, 'ct': 1694706571, 'ut': 1694706571}, {'id': 12, 'title': 'dddddd', 'completed': False, 'ct': 1694706594, 'ut': 1694706594}, {'id': 13, 'title': 'dddddd', 'completed': False, 'ct': 1694707342, 'ut': 1694707342}, {'id': 14, 'title': 'dddddd', 'completed': False, 'ct': 1694707490, 'ut': 1694707490}, {'id': 15, 'title': 'dddddd', 'completed': False, 'ct': 1694740785, 'ut': 1694740785}, {'id': 16, 'title': 'dddddd', 'completed': False, 'ct': 1694740881, 'ut': 1694740881}, {'id': 17, 'title': 'dddddd', 'completed': False, 'ct': 1694740939, 'ut': 1694740939}, {'id': 18, 'title': 'dddddd', 'completed': False, 'ct': 1694740971, 'ut': 1694740971}, {'id': 19, 'title': 'dddddd', 'completed': False, 'ct': 1694741018, 'ut': 1694741018}, {'id': 20, 'title': 'dddddd', 'completed': False, 'ct': 1694741036, 'ut': 1694741036}, {'id': 21, 'title': 'dddddd', 'completed': False, 'ct': 1694742835, 'ut': 1694742835}, {'id': 22, 'title': 'dddddd', 'completed': False, 'ct': 1694742852, 'ut': 1694742852}, {'id': 23, 'title': 'dddddd', 'completed': False, 'ct': 1694742875, 'ut': 1694742875}, {'id': 24, 'title': 'dddddd', 'completed': False, 'ct': 1694744839, 'ut': 1694744839}, {'id': 25, 'title': 'dddddd', 'completed': False, 'ct': 1694744867, 'ut': 1694744867}, {'id': 26, 'title': 'dddddd', 'completed': False, 'ct': 1694745034, 'ut': 1694745034}, {'id': 27, 'title': 'dddddd', 'completed': False, 'ct': 1694745051, 'ut': 1694745051}, {'id': 28, 'title': 'dddddd', 'completed': False, 'ct': 1694745237, 'ut': 1694745237}, {'id': 29, 'title': 'dddddd', 'completed': False, 'ct': 1694745384, 'ut': 1694745384}, {'id': 30, 'title': 'dddddd', 'completed': False, 'ct': 1694745889, 'ut': 1694745889}, {'id': 31, 'title': 'dddddd', 'completed': False, 'ct': 1694746101, 'ut': 1694746101}, {'id': 32, 'title': 'dddddd', 'completed': False, 'ct': 1694746182, 'ut': 1694746182}, {'id': 33, 'title': 'dddddd', 'completed': False, 'ct': 1694746366, 'ut': 1694746366}, {'id': 34, 'title': 'dddddd', 'completed': False, 'ct': 1694746401, 'ut': 1694746401}, {'id': 35, 'title': 'dddddd', 'completed': False, 'ct': 1694746898, 'ut': 1694746898}, {'id': 36, 'title': 'dddddd', 'completed': False, 'ct': 1694751000, 'ut': 1694751000}, {'id': 37, 'title': 'dddddd', 'completed': False, 'ct': 1694751113, 'ut': 1694751113}, {'id': 38, 'title': 'dddddd', 'completed': False, 'ct': 1694751131, 'ut': 1694751131}, {'id': 39, 'title': 'dddddd', 'completed': False, 'ct': 1694751266, 'ut': 1694751266}]
[{'id': 5, 'title': 'dddddd', 'completed': False, 'ct': 1694705822, 'ut': 1694705822}, {'id': 6, 'title': 'dddddd', 'completed': False, 'ct': 1694705829, 'ut': 1694705829}, {'id': 7, 'title': 'dddddd', 'completed': False, 'ct': 1694705966, 'ut': 1694705966}, {'id': 8, 'title': 'dddddd', 'completed': False, 'ct': 1694705976, 'ut': 1694705976}, {'id': 9, 'title': 'dddddd', 'completed': False, 'ct': 1694706174, 'ut': 1694706174}, {'id': 10, 'title': 'dddddd', 'completed': False, 'ct': 1694706542, 'ut': 1694706542}, {'id': 11, 'title': 'dddddd', 'completed': False, 'ct': 1694706571, 'ut': 1694706571}, {'id': 12, 'title': 'dddddd', 'completed': False, 'ct': 1694706594, 'ut': 1694706594}, {'id': 13, 'title': 'dddddd', 'completed': False, 'ct': 1694707342, 'ut': 1694707342}, {'id': 14, 'title': 'dddddd', 'completed': False, 'ct': 1694707490, 'ut': 1694707490}, {'id': 15, 'title': 'dddddd', 'completed': False, 'ct': 1694740785, 'ut': 1694740785}, {'id': 16, 'title': 'dddddd', 'completed': False, 'ct': 1694740881, 'ut': 1694740881}, {'id': 17, 'title': 'dddddd', 'completed': False, 'ct': 1694740939, 'ut': 1694740939}, {'id': 18, 'title': 'dddddd', 'completed': False, 'ct': 1694740971, 'ut': 1694740971}, {'id': 19, 'title': 'dddddd', 'completed': False, 'ct': 1694741018, 'ut': 1694741018}, {'id': 20, 'title': 'dddddd', 'completed': False, 'ct': 1694741036, 'ut': 1694741036}, {'id': 21, 'title': 'dddddd', 'completed': False, 'ct': 1694742835, 'ut': 1694742835}, {'id': 22, 'title': 'dddddd', 'completed': False, 'ct': 1694742852, 'ut': 1694742852}, {'id': 23, 'title': 'dddddd', 'completed': False, 'ct': 1694742875, 'ut': 1694742875}, {'id': 24, 'title': 'dddddd', 'completed': False, 'ct': 1694744839, 'ut': 1694744839}, {'id': 25, 'title': 'dddddd', 'completed': False, 'ct': 1694744867, 'ut': 1694744867}, {'id': 26, 'title': 'dddddd', 'completed': False, 'ct': 1694745034, 'ut': 1694745034}, {'id': 27, 'title': 'dddddd', 'completed': False, 'ct': 1694745051, 'ut': 1694745051}, {'id': 28, 'title': 'dddddd', 'completed': False, 'ct': 1694745237, 'ut': 1694745237}, {'id': 29, 'title': 'dddddd', 'completed': False, 'ct': 1694745384, 'ut': 1694745384}, {'id': 30, 'title': 'dddddd', 'completed': False, 'ct': 1694745889, 'ut': 1694745889}, {'id': 31, 'title': 'dddddd', 'completed': False, 'ct': 1694746101, 'ut': 1694746101}, {'id': 32, 'title': 'dddddd', 'completed': False, 'ct': 1694746182, 'ut': 1694746182}, {'id': 33, 'title': 'dddddd', 'completed': False, 'ct': 1694746366, 'ut': 1694746366}, {'id': 34, 'title': 'dddddd', 'completed': False, 'ct': 1694746401, 'ut': 1694746401}, {'id': 35, 'title': 'dddddd', 'completed': False, 'ct': 1694746898, 'ut': 1694746898}, {'id': 36, 'title': 'dddddd', 'completed': False, 'ct': 1694751000, 'ut': 1694751000}, {'id': 37, 'title': 'dddddd', 'completed': False, 'ct': 1694751113, 'ut': 1694751113}, {'id': 38, 'title': 'dddddd', 'completed': False, 'ct': 1694751131, 'ut': 1694751131}, {'id': 39, 'title': 'dddddd', 'completed': False, 'ct': 1694751266, 'ut': 1694751266}]
< Todo
id: (5)
title: (dddddd)
completed: (False)
ct: (1694705822)
ut: (1694705822)
>

[2023-09-15 12:15:27,007] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 89450
[2023-09-15 12:15:27,061] [ERROR] [launch.py:321:sigkill_handler] ['/usr/bin/python3', '-u', 'app.py', '--local_rank=0', '--deepspeed', '--deepspeed_config', 'ds_config.config'] exits with return code = -9
```

**Comment by win10ogod** [comment]
請您協助解除錯誤

**Comment by neromous** [comment]
在配置文件中将debug修改为false
